// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk5XY7VnfZ30p8XRY5mjDpKCsPHEKuY40',
    appId: '1:437467363341:web:52b2f407bd0ca43537bd44',
    messagingSenderId: '437467363341',
    projectId: 'chatsphere-b1f7a',
    authDomain: 'chatsphere-b1f7a.firebaseapp.com',
    storageBucket: 'chatsphere-b1f7a.firebasestorage.app',
    databaseURL: 'https://chatsphere-b1f7a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgNizOqR4F4rx7yi70oW7RLqM2ArxKEIE',
    appId: '1:437467363341:android:7289a8ec6e0f18ca37bd44',
    messagingSenderId: '437467363341',
    projectId: 'chatsphere-b1f7a',
    storageBucket: 'chatsphere-b1f7a.firebasestorage.app',
    databaseURL: 'https://chatsphere-b1f7a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH69SdiEVWO0LQ1HB5sfHKNkQfRUfiY3c',
    appId: '1:437467363341:ios:c82caac29641b14f37bd44',
    messagingSenderId: '437467363341',
    projectId: 'chatsphere-b1f7a',
    storageBucket: 'chatsphere-b1f7a.firebasestorage.app',
    iosBundleId: 'com.example.chatsphere',
    databaseURL: 'https://chatsphere-b1f7a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH69SdiEVWO0LQ1HB5sfHKNkQfRUfiY3c',
    appId: '1:437467363341:ios:c82caac29641b14f37bd44',
    messagingSenderId: '437467363341',
    projectId: 'chatsphere-b1f7a',
    storageBucket: 'chatsphere-b1f7a.firebasestorage.app',
    iosBundleId: 'com.example.chatsphere',
    databaseURL: 'https://chatsphere-b1f7a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk5XY7VnfZ30p8XRY5mjDpKCsPHEKuY40',
    appId: '1:437467363341:web:21a1177ff79044af37bd44',
    messagingSenderId: '437467363341',
    projectId: 'chatsphere-b1f7a',
    authDomain: 'chatsphere-b1f7a.firebaseapp.com',
    storageBucket: 'chatsphere-b1f7a.firebasestorage.app',
    databaseURL: 'https://chatsphere-b1f7a-default-rtdb.firebaseio.com',
  );
}
